name: Build and Upload Package

on:
  workflow_run:
    workflows:
      - CI - Tests - Security
    types:
      - completed

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
      #    if: |
      #      github.event.workflow_run.conclusion == 'success' &&
      #      startsWith(github.ref, 'refs/tags/') &&
      #      (github.base_ref == 'main' || github.base_ref == 'develop')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

          #      - name: Publish to PyPI
          #        env:
          #          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          #          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          #        run: twine upload dist/*
