name: Python package

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -e '.[dev]'
        with:
          name: coverage-report
          path: coverage.xml

      - name: Run tests with pytest
        run: pytest --cov-report=xml
        
      - name: Lint with flake8
        run: flake8 src tests
        
      - name: Lint with pylint
        run: pylint src tests
